### ISSUE TITLE
特定情况下无法使用directoryOpen成功读取文件

### ISSUE THREAD

**Issue by YJJMH** [GoogleChromeLabs/browser-fs-access#117]
操作系统：Windows
浏览器：Chrome，Edge
网络协议：https

描述：当网络协议是https时，并且目录的长度超过51个字符（英文字符）时，使用directoryOpen无法正常读取文件
错误：
![image](https://user-images.githubusercontent.com/35961785/175205415-cc119827-6b09-4e5c-b916-2e123887bedc.png)

麻烦请问一下这个是什么原因

**Comment by tomayac** [comment]
I just tried this on my machine (macOS), with a directory called `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` and it worked just fine. Since this sounds more like a Windows bug, could I ask you to create a [new.crbug.com](https://new.crbug.com/) with a minimal reproduction case? Thank you! If you paste the bug URL here, I'm happy to help triage it.

**Comment by YJJMH** [comment]
谢谢您的回复，但是目前我在中国，无法访问https://[chromiumbugs.appspot.com](https://chromiumbugs.appspot.com/)/，抱歉

**Comment by tomayac** [comment]
I just tried this on Windows via BrowserStack.com, and it worked fine. Could it be that your application uses a serialized directory handle to a directory that has been deleted?

<img width="1108" alt="Screen Shot 2022-06-27 at 10 10 13" src="https://user-images.githubusercontent.com/145676/175892332-8cb4a89e-5750-4c49-9592-3dfd576ef1c1.png">
<img width="1590" alt="Screen Shot 2022-06-27 at 10 12 34" src="https://user-images.githubusercontent.com/145676/175892339-5c809c1d-ce21-4585-b121-aba5bed22705.png">
