### ISSUE TITLE
No support for MIME charset?

### ISSUE THREAD

**Issue by Hawxy** [GoogleChromeLabs/browser-fs-access#148]
Is this an issue with the underlying spec? Trying to a save a blob of `type: 'text/csv;charset=UTF-8'` results in `Failed to execute 'showSaveFilePicker' on 'Window': Invalid type: text/csv;charset=utf-8`.

**Comment by tomayac** [comment]
First, I doubt that the file pickers in operating systems will meaningfully allow you to filter by MIME type parameters like the charset, but that being said, the spec [states](https://wicg.github.io/file-system-access/#:~:text=If%20parsedType%E2%80%99s%20parameters%20are%20not%20empty%2C%20then%20throw%20a%20TypeError.) explicitly that…

> If parsedType’s [parameters](https://mimesniff.spec.whatwg.org/#parameters) are not empty, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

…so that's working as per the spec algorithm. You need to remove MIME type parameters from your code.
