### ISSUE TITLE
fileOpen() function doesn't reject promise when user dismiss file picker prompt without selecting a file

### ISSUE THREAD

**Issue by mikeAtHexosIp** [GoogleChromeLabs/browser-fs-access#33]
The API works fine when selecting files and also handles rejection when the chosen file is not valid, but when the user dismiss the file picker prompt **without selecting any file**, execution gets stuck in **await fileOpen()**.

Code sample:
```
let fileHandle;
try {
   fileHandle = await fileOpen({
     mimeTypes: ['text/csv'],
     extensions: ['.csv'],
   });
} catch(error) {
   console.log(error); // Nothing happens here
}
```

**AC:**
Reject promise in fileOpen function when file picker prompt is dismissed

**Comment by tomayac** [comment]
Thanks for filing this, but I can't reproduce the reported issue. If you open the [demo](https://browser-fs-access.glitch.me/) and place a breakpoint on line 47 of [`script.mjs`](https://browser-fs-access.glitch.me/script.mjs) with DevTools and then click the **Open Image File** button, you can see that the demo catches the error and checks if the reason is an abort:

<img width="1677" alt="Screen Shot 2021-02-26 at 16 15 48" src="https://user-images.githubusercontent.com/145676/109318582-3f513180-784e-11eb-9edf-65dc4d356b01.png">

**Comment by Snugug** [comment]
@tomayac thanks for looking into this! I just gave this a try in Firefox Developer Edition, latest version, and if I cancel from **Open Image File** button it doesn't hit the breakpoint. I think it may have something to do with the polyfill fallback.

**Comment by tomayac** [comment]
Just discussed this offline with @Snugug. I’ll make sure this throws in the fallback case, too.

**Comment by tomayac** [comment]
@mikeAtHexosIp Thanks again for reporting this. I have just release `v0.14.0` that includes this fix.

**Comment by tomayac** [comment]
Safari Web Inspector:

<img width="1621" alt="Screen Shot 2021-02-26 at 17 47 19" src="https://user-images.githubusercontent.com/145676/109329314-b5f42c00-785a-11eb-8423-ca98e15a90b2.png">
