### ISSUE TITLE
it cannt work effectively on IOS Safari 15

### ISSUE THREAD

**Issue by shlroland** [GoogleChromeLabs/browser-fs-access#88]
its behavior is I can open the file picker,but when i finish the seleting work,  the Promise cannt be fullfilled or rejected

**Comment by tomayac** [comment]
Sigh, we thought this was solved via #74 that closed #72, but currently the only way that seems to work reliably is what @dwelle has [implemented for Excalidraw](https://github.com/excalidraw/excalidraw/blob/24bf4cb5fb6f7028f11796b1cb39506976d274e0/src/data/filesystem.ts#L48-L86). Could you try this approach and come back with your results?

**Comment by dwelle** [comment]
Lemme know if you want me to port it from excal.

**Comment by tomayac** [comment]
I wonder if this has to do with HEIC images. For example, if I go to https://browser-fs-access.glitch.me/ and open an image from Photos on iOS Safari, it would never work. If I, however, open a `.png` from Files, it works perfectly fine, and so do `.txt` files. It also works fine for Excalidraw files, which may or may not have to do with @dwelle's approach.

I more and more suspect iOS has a HEIC problem, since the same code https://browser-fs-access.glitch.me/ works perfectly fine for image files I try on macOS Safari. Note that the `input[accept]` value is `image/jpg,image/png,image/gif,image/webp,.jpg,.jpeg,.png,.gif,.webp`, so _not_ `image/*` and _excluding_ `.heic` or any variant of `image/heif`, `image/heic`, `image/heif-sequence`, or `image/heic-sequence`. And yet Safari on iOS and macOS let me happily open `.heic` images.

**Comment by dwelle** [comment]
I don't recall, and I believe at the time I didn't have access to iOS so I was reproducing only on FF and MacOS Safari, and there it didn't work for `.excalidraw`/`.json`/`.png` files indiscriminately.
